version: "3"
services: 
  react :
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /home/swucs/projects/dockerApp/node_modules
      - ./:/home/swucs/projects/dockerApp
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/swucs/projects/dockerApp/node_modules
      - ./:/home/swucs/projects/dockerApp
    command: ["npm", "run", "test"]